M48
; DRILL file {KiCad 9.0.0} date 2026-03-10T11:47:07+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-10T11:47:07+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X154.5Y-104.0
X154.5Y-149.5
X234.5Y-94.5
X277.5Y-94.5
X277.5Y-149.5
M30
