"""Compatibility wrapper for running the voltage simulation."""

from .main import main
import serial
import time

# --- CONFIGURATION ---
# Change this to match your Arduino's port (e.g., 'COM3' for Windows, '/dev/ttyUSB0' for Linux/Mac)
SERIAL_PORT = 'COM3' 
BAUD_RATE = 115200

def main():
    print(f"Connecting to {SERIAL_PORT} at {BAUD_RATE} baud...")
    
    try:
        # Open serial connection
        ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=1)
        time.sleep(2)  # Give Arduino time to reset after opening connection
        
        # Clear any startup messages generated by initialize_ADS1256()
        ser.reset_input_buffer() 
        
        print("Sending 'C' command to start continuous stream...")
        ser.write(b'C')

        # IF AIN0 AND AIN1 ENABLE THIS TO CHANGE OR LET USER CONFIGURE WHICH PIN TO READ
        '''
        # Ask the user for input, or press Enter for default
        cmd_input = input("Enter channel command (e.g., 'C2 4') or press Enter for default 'C': ").strip()
        
        if cmd_input == "":
            cmd_input = "C"
            
        # Add a newline \n so Arduino's parseInt() processes it instantly
        command_to_send = f"{cmd_input}\n".encode('utf-8')
        
        print(f"Sending command: '{cmd_input}' ...")
        ser.write(command_to_send)
        '''
        
        # Wait for the stream to start
        while True:
            line = ser.readline().decode('utf-8').strip()
            if line == "*STREAM_START":
                print("Stream started successfully! Press Ctrl+C to stop.\n")
                break
                
        # --- CONTINUOUS READING LOOP ---
        while True:
            if ser.in_waiting > 0:
                line = ser.readline().decode('utf-8').strip()
                
                # Ignore empty lines or debug messages (which you prefixed with '*')
                if line and not line.startswith('*'):
                    try:
                        # Parse the CSV data: "Voltage,Current"
                        data = line.split(',')
                        if len(data) == 2:
                            voltage = float(data[0])
                            current = int(data[1])
                            
                            # You can now process 'voltage' and 'current' however you like
                            # For example, saving to a file, plotting, or just printing:
                            print(f"Voltage: {voltage: 10.8f} V  |  Current: {current:3} mA")
                            
                    except ValueError:
                        print(f"Failed to parse data: {line}")
                        
    except KeyboardInterrupt:
        print("\nCtrl+C detected. Stopping the stream...")
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        # Ensure we always stop the Arduino and close the port cleanly
        if 'ser' in locals() and ser.is_open:
            ser.write(b's')      # Send stop command
            time.sleep(0.5)      # Wait a moment for Arduino to process it
            ser.reset_input_buffer()
            ser.close()
            print("Serial port closed.")

if __name__ == '__main__':
    main()